Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server-2022" # Use a Windows Server 2022 box
  config.vm.provider "vmware_desktop" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.network "private_network", type: "dhcp"

  config.vm.communicator = "winrm"  # Required for Windows provisioning

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.compatibility_mode = "2.0"
  end
end
