---
- name: Install Ansible Galaxy
  hosts: localhost
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Ansible
      pip:
        name: ansible
        state: present

    - name: Install Ansible Galaxy role
      command: ansible-galaxy install geerlingguy.apache
