---
- name: Linux Getting Started First Playbook Extended
  hosts: all
  become: yes  # Run tasks with elevated privileges (sudo)
  gather_facts: yes  # Gather facts about the Linux system
  tasks:

    - name: Display system information
      ansible.builtin.debug:
        msg: >
          The hostname is {{ ansible_facts['hostname'] }} and the OS is {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}.

    - name: Update the hostname
      ansible.builtin.hostname:
        name: linux-changed
      when: ansible_facts['hostname'] != 'linux-changed'

    - name: Re-gather facts to reflect the new hostname
      ansible.builtin.setup:

    - name: Display the updated system information
      ansible.builtin.debug:
        msg: >
          The new hostname is {{ ansible_facts['hostname'] }} and the OS is {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}.